# docker-compose.yml is the file that will allow us to set-up and run our containers with our own configuration
version: '3.8'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    networks:
      - best_network
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    networks:
      - best_network
    volumes:
      - wordpress-data:/var/www/html/wordpress
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    networks:
      - best_network
    volumes:
      - wordpress-data:/var/www/html/wordpress
    restart: always
    env_file:
      - .env

networks:
  best_network:

volumes:
  mariadb-data:
    driver_opts:
      type: none
      device: /home/wbekkal/data/mysql
      o: bind
  wordpress-data:
    driver_opts:
      type: none
      device: /home/wbekkal/data/html/wordpress
      o: bind
